build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      stack: python 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      stack: python 3

install:
  - sudo python -m pip install pytest-cov

test_script:
  - pytest --cov=./ --cov-report=xml
  - printenv
  - bash <(curl -s https://codecov.io/bash) -t c32fe4bc-6645-446e-b079-faeedcd18167

