build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      stack: python 3

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - pip install codecov
  - pip install pytest-cov

test_script:
  - pytest --cov=./ --cov-report=xml
