build: false

environment:
  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "%PYTHON%/Scripts/pip.exe install pytest-cov"

test_script:
  - "%PYTHON%/Scripts/pytest --cov=./ --cov-report=xml"
